[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["sobalib"]

[project]
name = "soba"
version = "0.0.1"
dependencies = [
    "torch",
    "torchvision",
    "torchtnt",
    "opt_einsum",
    "einops",
    "transformers",
    "sparsemax",
    "matplotlib",
]
requires-python = ">=3.11"
authors = [
  {name = "Can Yaras", email = "cjyaras@gmail.com"},
]
description = "Stuctured Optimal Bi-directional Attention."
readme = "README.md"
license = {file = "LICENSE"}
keywords = []

